### ISSUE TITLE
Type error for objectArray

### ISSUE THREAD

**Issue by KarmaPoliceT2** [OfficeDev/office-scripts-docs#376]
Copy pasting this into excel scripts throws an error "Office Scripts cannot infer the data type of this variable. Please declare a type for the variable." for the line "let objectArray = []" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85ab721c-371b-8901-abdc-adbbcbd2c81b
* Version Independent ID: 5cd477ae-cce5-a942-4297-6f23aebd3267
* Content: [Output Excel data as JSON - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/get-table-data)
* Content Source: [docs/resources/samples/get-table-data.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/resources/samples/get-table-data.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Thanks for reporting this @KarmaPoliceT2. I'll investigate this and fix the sample soon.

**Comment by AlexJerabek** [comment]
Hi @KarmaPoliceT2,

I'll post a PR to address this soon. The issue relates to the recent change of Office Scripts no longer supporting the `any` type. You can read more about that [here](https://docs.microsoft.com/office/dev/scripts/develop/typescript-restrictions#no-any-type-in-office-scripts). The fix is to give an explicit type to the table row array and values passed to that array.
