### ISSUE TITLE
Convert CSV files to Excel : Runtime error: Line 28: Cannot read property 'getRangeByIndexes' of undefined

### ISSUE THREAD

**Issue by mlamberty** [OfficeDev/office-scripts-docs#433]
Power Automate script that creates  4 csv files based on Graph API response. unable to run script at the end. largest csv fiile has 147 rows. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fdee872-3dfe-61b6-f824-dc8c74625c36
* Version Independent ID: c4481c81-ebae-7b3a-5da9-1757fb575188
* Content: [Convert CSV files to Excel workbooks - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/convert-csv)
* Content Source: [docs/resources/samples/convert-csv.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/resources/samples/convert-csv.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @mlamberty,

Thanks for sharing your issue. I'm going to assume this error is coming from these two lines of the sample (please correct me if I'm wrong):
```
  // Put the data in the worksheet.
  let sheet = workbook.getWorksheet("Sheet1");
  let range = sheet.getRangeByIndexes(0, 0, data.length, data[0].length);
```

The error message "Cannot read property 'getRangeByIndexes' of undefined" implies the object 'getRangeByIndexes' is being called on does not exist. In this case, that's the worksheet. Does your workbook have a worksheet named "Sheet1"? If not, `workbook.getWorksheet("Sheet1")` will return `undefined`.

Or can get around this problem by doing one of the following:
- Manually creating a worksheet named "Sheet1" in the workbook.
- Change the script to create a new worksheet each time it runs and call `getRangeByIndexes` on the new worksheet.
- Change the script to check if "Sheet1" exists and, if it doesn't, create it.

I should mention that "Sheet1" is only used in the sample as a placeholder (since that's a default name). The worksheet can be called whatever you want.

Does that information help?
