### ISSUE TITLE
Script Error for analyze-web-downloads file

### ISSUE THREAD

**Issue by MisterMxyztplk** [OfficeDev/office-scripts-docs#436]
Hi,

This script produces an error and will not run in Excel.

Error message:
See line 46, column 7: Office Scripts cannot infer the data type of this variable. Please declare a type for the variable.

Does anyone have any suggestions for a newb?

Thanks

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44f44854-5d15-667f-3dc2-5dff9c1fa7dd
* Version Independent ID: 3e8f2e24-86b2-565d-322a-43b8edcb4882
* Content: [Office Scripts sample scenario: Analyze web downloads - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/resources/scenarios/analyze-web-downloads)
* Content Source: [docs/resources/scenarios/analyze-web-downloads.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/resources/scenarios/analyze-web-downloads.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @MisterMxyztplk,

I'll take a look and see if I can reproduce the issue. 

In general, that error refers to Office Scripts not supporting variables of `any` type. This article describes those scenarios and gives some workarounds: https://docs.microsoft.com/en-us/office/dev/scripts/develop/typescript-restrictions#no-any-type-in-office-scripts

**Comment by AlexJerabek** [comment]
Hi @MisterMxyztplk,

The change needed in the script is switching the line `let newCol = [];` to `let newCol: (boolean | string)[][] = [];`. This is because the first version does not specify a type and it cannot be implicitly determined. Multiple types are added (boolean for the data and string for the header), so we need to explicitly let the script know that's what's going in the array.

PR #437 will address this in the documentation.
