### ISSUE TITLE
Describe the timeout when the scripts are executed  via Power Automate

### ISSUE THREAD

**Issue by MiyukiAmino** [OfficeDev/office-scripts-docs#440]
The script which is successful via Excel is sometimes failed via Power Automate due to timeout. #504 GatewayTimeout
Could you describe it as a limitation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4085c6ff-856c-4704-8d72-5ef0ca1f64c1
* Version Independent ID: 92eda514-0e20-3add-4b61-62d82d210549
* Content: [Platform limits and requirements with Office Scripts - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/testing/platform-limits#power-automate)
* Content Source: [docs/testing/platform-limits.md](https://github.com/OfficeDev/office-scripts-docs/blob/master/docs/testing/platform-limits.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by RuoyingLiang** [comment]
Thanks for reaching out. @AlexJerabek, could you help to take a look?

**Comment by AlexJerabek** [comment]
Thank you for reporting this documentation gap @MiyukiAmino. I will begin investigating and work on updating the documentation accordingly.

**Comment by AlexJerabek** [comment]
Hi @MiyukiAmino,

I've created PR https://github.com/OfficeDev/office-scripts-docs/pull/443 to highlight this timeout. If you'd like specific advice about optimizing your script to avoid the timeout, I'd recommend posting on [Stack Overflow with the tag office-scripts](https://stackoverflow.com/questions/tagged/office-scripts). Stack Overflow is a good forum our team and members of the community to help with specific issues.

Please let me know if you have any concerns with the PR or any other questions. Otherwise, this issue will close when the PR is checked in.
