### ISSUE TITLE
Combine worksheets into a single workbook - not working ?

### ISSUE THREAD

**Issue by Kaddrik** [OfficeDev/office-scripts-docs#463]
Hello, 

hope you're doing good.

I found your page about combining worksheets into a single workbook that i found very interesting cause it's exactly what i'm trying to do.

https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/combine-worksheets-into-single-workbook

The problem is i'm trying to combine the content of multiple CSV files into 1 workbook that i would use for consolidation and do this into SharePoint online.

to test your solution, i created 2 workfbooks and got an additional one  holding the result of the consolidation and i do this in OneDrive for business.  reflecting the exact same thing that you did doesn't work...or at least i don't understand where my mistake is. it stops at the second "Run script" saying  "workbook not found" ...while it found the 3 of them at the first step

then i readapted a little bit using a Get files (properties only) - SharePoint action - it stops with the same error at the first step. Is there anyway you cold help me solve this ?

Thanks a lot and regards,
Cedric

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 688cb5b0-672f-8480-8943-6e4bc403d6b9
* Version Independent ID: 61518540-2796-b66f-4bc7-aef0eca420ad
* Content: [Combine workbooks into a single workbook - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/combine-worksheets-into-single-workbook)
* Content Source: [docs/resources/samples/combine-worksheets-into-single-workbook.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/combine-worksheets-into-single-workbook.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Kaddrik** [comment]
Ah wait...ok, i removed the workbook i want to use for the consolidation from the folder and now i get another error...

We were unable to run the script. Please try again.
Office JS error: Line 7: Workbook addWorksheet: The argument is invalid or missing or has an incorrect format.
clientRequestId: 4c0829e7-0e1f-4837-8bca-51f1a591fd84

hmm...

**Comment by AlexJerabek** [comment]
Hi @Kaddrik,

Thanks for reaching out. Let me try to offer some advice to help unblock you.

First, are you able to get the sample working without any modifications? Getting CSV files working is an involved step (there's a [whole other sample on that](https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/convert-csv)), so it's good to test parts of your flow separately. 

In your first post, you mention getting a "Workbook not found" error. Is this in relation to the workbook you're creating during your flow? Or does this workbook already exist? In the former, double check that the dynamic content is accurate (after a failed flow test, you can expand the values in the flow and see what's actually being used). In the later, be sure to use the file picker instead of manually typing file names. This gets the correct file ID.

![image](https://user-images.githubusercontent.com/38896772/155762012-82a515b3-5aee-45fc-a394-1d9f9131aeaf.png)

As for the script error at `Workbook.addWorksheet`, that's implying the string being used as the worksheet name is invalid. My guess is that the `workbookName: string` argument being passed in is in some way incorrect or missing. It's hard to say without seeing the full context of the flow. Screenshots of the flow steps help with this.

As a general note, while I'm happy to help you here in the Office Scripts docs, you might be better served posting on [Stack Overflow](https://stackoverflow.com/questions/tagged/office-scripts) or to the [Power Automate forums](https://powerusers.microsoft.com/t5/Building-Flows/bd-p/BuildingFlows). There, members of the community can see your post and help out as well. It'll also help others with similar problems find the solution later.

**Comment by Kaddrik** [comment]
Hello @AlexJerabek ,

Thanks for your answer. Well I wrote here cause there was a feedback link atthe bottom of the page and since it's a microsoft page i wanted to be sure i would ask the question to the author. I wasn't sure i could go on Stackoverflow. anyway, i will answer here...

I created a xlsx file that i called Template, where i added your 2 scripts as they are on the page. i didn't modify anything.
then i put 2 xlsx file in a folder called "Test". so i have my template file at the root of my onedrive and the 2 others in a sub folder.

i first tried to put the 3 files together in the "test" folder... that's how i got the first error "workbook not found" then i moved the "Template.xlsx" workbook to the root and at that time i got the second error message.

so the scripts are identical and the workflow as well ... hmm... i don't know how to add pictures here :-( but yes, mine is exactly the same and yes i did it as you explained.. so not really what's wrong....

about the second error, since i'm using the exact same code as you wrote on the page so i just have it like this ...

 let sheet = workbook.addWorksheet(`${workbookName}.${value.name}`);

aaaah so you expect me to write down "Template" instead of "workbookName", right ?

and finally, I will have a look at the other post since , in my case i start with CSV files that are created by a Flow. So that means, i first have to convert the CSV files into workbook and then do this second part... if i correctly understand ...

Thanks a lot again

**Comment by AlexJerabek** [comment]
GitHub lets you add pictures by pasting them directly into the reply text box. If you're on Windows, you can take screenshots of your flow steps by pressing **Windows Key + Shift + S** and selecting the relevant part of the screen, then pasting that snip here.

As for the script steps, you don't need to replace anything in the line 
```
let sheet = workbook.addWorksheet(`${workbookName}.${value.name}`);
```

That's a [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) that allows strings to have variables inserted into them without having to do string concatenation (`workbookName + "." + value.name`).

As is, that second script adds worksheets like this:
![image](https://user-images.githubusercontent.com/38896772/155786431-56faea19-b318-40b1-8c08-e56b12423584.png)


The Template file mentioned in the "CSV" sample only exists to create a brand new Excel file. So that is used for each new .xslx file. However, the merged file in the "Combine" sample doesn't need a template if you manually create it.

**Comment by Kaddrik** [comment]
well, for the copy/paste, that's what i did but it didn't work.

"Template" is the name that i used for my file where i added the scripts to and that should get all the tabs... maybe i should have call it another way to be clearer :-P

ok so at the end, there's nothing to change in the scripts, the fact that i just copied them and pasted them into my "Template.xlsx" file is correct. but it doesn't work anyway so...i don't understand what's wrong.. :-(

**Comment by Kaddrik** [comment]
@AlexJerabek ,

ok i don't understand. I still didn't change anything and i try it again but now it works...

but I have 2 workbooks that should go into one...and in the destination one (the one i called "Template") now i have  4 tabs. first one is the Sheet1 that is the default one when you open a blank xlsx file...

![image](https://user-images.githubusercontent.com/72975053/155796008-7e878a68-370a-4810-9813-8cb8e28fe33b.png)

and then i have 3 tabs.... first one (the one after Sheet1) is useless but i don't understand where it come from.
and....is it possible to change the name of the other tabs ?

thanks

**Comment by Kaddrik** [comment]
ah now the copy paste works as well 😂

**Comment by AlexJerabek** [comment]
Thanks for sharing that. I'm glad we seem to be making progress.

The script shouldn't be able to use the variable names as information, so I'm not sure how that worksheet called "${workbookName},${value.name}" is being created. Double check there's not an extra line in that script (or just re-copy the original sample script.

If possible, could you also share a picture or your flow? Here's the complete flow I've created form the sample and am using to help:

![image](https://user-images.githubusercontent.com/38896772/155810516-dff1caa4-3c71-4120-8e43-7bb04b24bcbc.png)

**Comment by Kaddrik** [comment]
Hello @AlexJerabek ,

So now everything seems to be working...which is strange cause i didn't change anything from the first post to the last one. The only thing i did was trying again and again so i really don't know what happened. I even managed to adapt it to my SharePoint list. I will show here how i did it for SharePoint

![image](https://user-images.githubusercontent.com/72975053/155847801-422937f5-1163-4a36-994c-97fba64c9480.png)


Thanks a lot again for all your help  

.... Now i will try the other post converting the csv to xlsx 😁

**Comment by AlexJerabek** [comment]
I'm glad it all worked out, even if we're not sure what changed. I'm going to close this issue, but please raise a new one if you encounter any problems with the CSV conversion scripts.
