### ISSUE TITLE
Convert CSV files to Excel workbooks - Office JS error: Line 33: Worksheet getRangeByIndexes

### ISSUE THREAD

**Issue by thanhrieker** [OfficeDev/office-scripts-docs#470]
Hello,

I just got error from Power Automate after implement example convert CSV to Excel by following article bellow:

## Article URL
[Document about convert CSV to Excel](https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/convert-csv)

## Issue
All step are working well but with large CSV file I run in [troubleshooting](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/convert-csv.md#troubleshooting) and got error:
```
We were unable to run the script. Please try again.
Office JS error: Line 33: Worksheet getRangeByIndexes: The request failed with status code of 413.
```

Could you please have a look?

Thanks you
Thanh

**Comment by ElizabethSamuel-MSFT** [comment]
@thanhrieker Thanks for letting us know about this.

@AlexJerabek Can you take a look?

Thanks.

**Comment by thanhrieker** [comment]
> Thanks for reporting this @thanhrieker.
> 
> Is this error happening when you run the sample in Excel or through Power Automate? If you're seeing it in Excel, can you please share the Session ID? You can find that by going to **File** > **About**. That will help our team debug the error.
For sample file the script running well through Power Automate. The error just occur when I run own large file.

> 
> ![image](https://user-images.githubusercontent.com/38896772/158234812-d5568b3d-66c7-4437-81a8-1897b4c56b13.png)
> 
> If possible, could you also provide a version of the .csv file that is generating the error? Please make sure it does not contain any personal or sensitive information before linking to it. Thanks!

Sorry but I can not provide a version of the .csv file. But I can tell you the file with more then 46.000 rows and 62 columns. Split by semicolon.

Thanks you for your quick reply
Thanh

**Comment by AlexJerabek** [comment]
Thank you for the response @thanhrieker.

It looks like that error is generated when too much information is being transferred. If that's coming through Power Automate, I think you're hitting this limit:
https://powerusers.microsoft.com/t5/General-Power-Automate/Error-code-413-when-using-Get-File-Content-on-files-larger-than/td-p/212326
You could also be bumping against the 5MB read/write limit of Excel: https://docs.microsoft.com/en-us/office/dev/scripts/testing/platform-limits#excel

If it's the latter, you could try the second version of the CSV script (found [here](https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/convert-csv) that goes row-by-row. That should split the operations into smaller pieces. However, you may then hit the timeout limit in Power Automate.

Let me tag @GeoffRen to see if he has any insight or suggestions.

**Comment by thanhrieker** [comment]
> 

Thanks you for your information. Yes, you are right. Our csv file come to the limit of Excel.

> If it's the latter, you could try the second version of the CSV script (found [here](https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/convert-csv) that goes row-by-row. That should split the operations into smaller pieces. However, you may then hit the timeout limit in Power Automate.

I already try both but:
- The first script got error: "The number of rows or columns in the input array doesn't match the size or dimensions of the range."
- Then try second script got that I report on this issue.

Thanks
Thanh

**Comment by AlexJerabek** [comment]
Just to confirm, you're using the second script because your CSV file doesn't have equal sized rows, correct? Something like this?
```
1,2
3,4,5
6,7
```

**Comment by AlexJerabek** [comment]
Also @wandyezj,
Any idea why this script is hitting the Excel limit? The write operations are separated in the loop by reads, which should force a trip to the server, right?
```
function main(workbook: ExcelScript.Workbook, csv: string) {
  let sheet = workbook.getWorksheet("Sheet1");

  /* Convert the CSV data into a 2D array. */
  // Trim the trailing new line.
  csv = csv.trim();

  // Split each line into a row.
  let rows = csv.split("\r\n");
  rows.forEach((value, index) => {
    /*
     * For each row, match the comma-separated sections.
     * For more information on how to use regular expressions to parse CSV files,
     * see this Stack Overflow post: https://stackoverflow.com/a/48806378/9227753
     */
    let row = value.match(/(?:,|\n|^)("(?:(?:"")*[^"]*)*"|[^",\n]*|(?:\n|$))/g);

    // Check for blanks at the start of the row.
    if (row[0].charAt(0) === ',') {
      row.unshift("");
    }

    // Remove the preceding comma.
    row.forEach((cell, index) => {
      row[index] = cell.indexOf(",") === 0 ? cell.substr(1) : cell;
    });

    // Create a 2D-array with one row.
    let data: string[][] = [];
    data.push(row);

    // Put the data in the worksheet.
    let range = sheet.getRangeByIndexes(index, 0, 1, data[0].length);
    range.setValues(data);
  });

  // Add any formatting or table creation that you want.
}
```

**Comment by thanhrieker** [comment]
> Just to confirm, you're using the second script because your CSV file doesn't have equal sized rows, correct? Something like this?
> 
> ```
> 1,2
> 3,4,5
> 6,7
> ```

Hello,

Please have a look example CSV file in attachment.

Thanks
Thanh
[help_csv.txt](https://github.com/OfficeDev/office-scripts-docs/files/8278277/help_csv.txt)

**Comment by AlexJerabek** [comment]
Thanks for the sample file. I'll take a look.

**Comment by AlexJerabek** [comment]
Thank you @thanhrieker. I am able to reproduce the error locally now. My suspicion was correct the write operations are getting batched, so the script is trying to write all 46000 rows at once.

I'll try to figure out a workaround for this. My thought is that if we can break this up to batches of 10000 rows, everything should be fine.

**Comment by AlexJerabek** [comment]
Okay, I think I have made progress in finding a solution for you. 

First, thank you for highlighting the gap in the article's coverage of semicolon-separated value files. I will update the article to be more inclusive of other systems.

As for the main concern, we can force the script to sync with the workbook at certain intervals, making sure the amount of data is less than the size limit. A `console.log` statement causes this sync. I added a counter to the row parser and have the script write a line to the console every 2500 lines. The higher this number, the faster the script will be, but the smaller the data chunks need to be. Here's my version of the script:

```
function main(workbook: ExcelScript.Workbook, csv: string) {
  let sheet = workbook.getWorksheet("Sheet1");
  /* Convert the CSV data into a 2D array. */
  // Remove any Windows \r characters
  csv = csv.replace(/\r/g, "");

  // Split each line into a row.
  let rows = csv.split("\n");
  let rowCount = 0;
  rows.forEach((value, index) => {
    if (value.length > 0) {
      /*
       * For each row, match the comma-separated sections.
       * For more information on how to use regular expressions to parse CSV files,
       * see this Stack Overflow post: https://stackoverflow.com/a/48806378/9227753
       */
      let row = value.match(/(?:;|\n|^)("(?:(?:"")*[^"]*)*"|[^";\n]*|(?:\n|$))/g);

      // Check for blanks at the start of the row.
      if (row[0].charAt(0) === ';') {
        row.unshift("");
      }

      // Remove the preceding comma.
      row.forEach((cell, index) => {
        row[index] = cell.indexOf(";") === 0 ? cell.substr(1) : cell;
      });

      // Create a 2D-array with one row.
      let data: string[][] = [];
      data.push(row);

      // Put the data in the worksheet.
      let range = sheet.getRangeByIndexes(index, 0, 1, data[0].length);
      range.setValues(data);

      rowCount++;
      if (rowCount % 2500 === 0) {
        console.log("Syncing 2500 rows.");
      }
    }
  });
}
```

That said, you may still hit timeout issues in Power Automate. Let me know if this unblocks you, otherwise I can keep looking for solutions.

**Comment by thanhrieker** [comment]
Thanks you @AlexJerabek for updated script. I will try then let you know.

Have a nice day
Thanh

**Comment by thanhrieker** [comment]
@AlexJerabek the error 413 is gone but time out come:

`{
  "error": {
    "code": 504,
    "source": "europe-002.azure-apim.net",
    "clientRequestId": "38d75597-e1ff-4369-abc9-70ec6f8f8d9c",
    "message": "BadGateway",
    "innerError": {
      "status": 504,
      "message": "Request to Graph API has timed out.\r\nclientRequestId: 38d75597-e1ff-4369-abc9-70ec6f8f8d9c",
      "error": {
        "message": "Request to Graph API has timed out."
      },
      "source": "excelonline-ne.azconn-ne.p.azurewebsites.net"
    }
  }
}`

**Comment by AlexJerabek** [comment]
Thanks @thanhrieker. I was afraid we'd hit that timeout.

 @GeoffRen @wandyezj @gergzk, any ideas to help here? Basically, the CSV data is too large to write without reaching the Excel data limit, but batching the write operations causes it to exceed the Power Automate timeout limit.

**Comment by AlexJerabek** [comment]
Hi @thanhrieker,

Juist wanted to check in and say I haven't forgotten about this issue. I'm trying to create a solution that will partially parse the file before timing out, then call the script again. Hopefully I can have something to help you next week.

**Comment by thanhrieker** [comment]
> Hi @thanhrieker,
> 
> Juist wanted to check in and say I haven't forgotten about this issue. I'm trying to create a solution that will partially parse the file before timing out, then call the script again. Hopefully I can have something to help you next week.

Thanks
Thanh

**Comment by AlexJerabek** [comment]
Hi @thanhrieker,

I wanted to share a solution I came up with you. The idea is that the script is run multiple times on different parts of the workbook. For testing purposes, I changed flow to only run on one file, but the solution should still work with multiple. I'm also using the version of the script that parses based on semicolons, instead of commas.

## Scripts

1. Create a script to convert the string data from the data file into an array. I named this one "Parse into Array".
```
function main(workbook: ExcelScript.Workbook, csv: string): string[] {
  let sheet = workbook.getWorksheet("Sheet1");
  /* Convert the CSV data into a 2D array. */
  // Remove any Windows \r characters
  csv = csv.replace(/\r/g, "");

  // Split each line into a row.
  let rows = csv.split("\n");
  return rows;
}
```

2. Create a script to set the values of 2500 rows at a time. I named this script "Convert SSV". This script takes in the previous array. It also needs to know the current row the whole process is on, as tracked by `index`. It'll return `index` too, so the flow can pass it back into the script. Note that we'll return `-1` once the whole process is complete.

```
function main(workbook: ExcelScript.Workbook, rows: string[], index: number): number {
  let sheet = workbook.getWorksheet("Sheet1");

  while (index < rows.length) {
    if (rows[index].length > 0) {
      let row = rows[index].match(/(?:;|\n|^)("(?:(?:"")*[^"]*)*"|[^";\n]*|(?:\n|$))/g);

      // Check for blanks at the start of the row.
      if (row[0].charAt(0) === ';') {
        row.unshift("");
      }

      // Remove the preceding comma.
      row.forEach((cell, index) => {
        row[index] = cell.indexOf(";") === 0 ? cell.substr(1) : cell;
      });

      // Create a 2D-array with one row.
      let data: string[][] = [];
      data.push(row);

      // Put the data in the worksheet.
      let range = sheet.getRangeByIndexes(index, 0, 1, data[0].length);
      range.setValues(data);

      index++;
      if (index % 2500 === 0) {
        return index;
      }
    }
  }

  return -1;
}
```

## Flow

1. Setup the basics. This includes parsing the template file, getting the file content from the CSV/SSV file, and creating the empty .xlsx file. Like I said, this is just for one file, so it's hard-coded to use a file called "test.csv".

![image](https://user-images.githubusercontent.com/38896772/162049487-02c08f5e-af90-4077-b6fe-3240ad379dcf.png)

2. Initialize the row counter variable using a Power Automate variable controller. I named it `index` to match the script's parameter name. Start at value `0` to begin at the first row.

![image](https://user-images.githubusercontent.com/38896772/162049689-84d6446a-1e74-475a-ba95-3faebb4c2485.png)

3. Run the first script. Use the data from the CSV/SSV file as the argument.

![image](https://user-images.githubusercontent.com/38896772/162049897-5cd2f439-09d1-42ce-b7be-2724964b1847.png)

4. Create a loop control. Until `index` is less than `0`, keep going. This means the second script hasn't hit the end of the array.

![image](https://user-images.githubusercontent.com/38896772/162050060-a5250611-bf1b-4901-b00d-ffe89301c89c.png)

5. Run the second script. Use the array generated by the first script as the argument and the flow variable as the index. After the script is run, set the index variable to be the returned value (the current row).

![image](https://user-images.githubusercontent.com/38896772/162050280-a9f6e837-3e03-442d-913b-6fae3a495b72.png)

6. Test it out! A 45,000-row file based on the sample data you provided took about 20 minutes to complete. As long as no single Power Automate action takes too long, that should be fine.



I fully realize this is a complex solution. Please let me know if you have trouble implementing it. If everything works out, I'll look into adding this guidance into the Office Scripts documentation.

**Comment by thanhrieker** [comment]
Perfect, 

Thanks for the update.

I will try and let you know later on.

Regards
Thanh

**Comment by thanhrieker** [comment]
Hello @AlexJerabek,

I just run script. No more time out but script tell us "Wokbook not found":

```
{
  "message": "We were unable to run the script. Please try again.\nWorkbook not found.\r\nclientRequestId: b95b2814-bf3c-4b0c-89b8-8fb38bdfd31f",
  "logs": []
}
```

Strange?

Best regards
Thanh
