### ISSUE TITLE
Sample code: Add worksheets does not work when entered unaltered

### ISSUE THREAD

**Issue by JoannaNaomi** [OfficeDev/office-scripts-docs#491]
## Article URL
 https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/combine-worksheets-into-single-workbook

## Issue
 I have tried to use the sample script as is without any alterations to combine two workbooks into one. The first sample code for Sample code: Return worksheet data works fine but when I enter (I have tried typing multiple times and copy paste directly) the sample code for Sample code: Add worksheets it will not work. The error message I get is "Line 9: cannot read properties of undefined (reading 'forEach') - please see screenshot.

Any assistance troubleshooting would be much appreciated :) - I am new to Automate and Power Automate...

![image](https://user-images.githubusercontent.com/104799756/166336887-1f1c0
![combine files issue](https://user-images.githubusercontent.com/104799756/166336938-634265ee-c23d-48da-93f4-6ab7f7c2aa5b.png)
d0c-e6d1-4940-802a-d4a424e8ecae.png)

**Comment by AlexJerabek** [comment]
Hi @JoannaNaomi,

Thanks for reaching out. Let me see if I can help you get the scripts and flow working.

Whenever there's a "cannot read properties of undefined" error, it means an object in that line doesn't exist. In this case, that would be `worksheetInformation`, because it does not get a value unless data is provided through Power Automate. Anything defined as an [additional parameter](https://docs.microsoft.com/en-us/office/dev/scripts/develop/power-automate-integration#main-parameters-pass-data-to-a-script) for the script needs a value provided when called in Power Automate. This is what Step 5 of [building the flow](https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/combine-worksheets-into-single-workbook#power-automate-flow-combine-worksheets-into-a-single-workbook) describes.

I would recommend completing the flow before trying to run the scripts through the Code Editor. Be sure to have multiple workbook files in the "output" folder, so you can see them all getting added to the final workbook.

If you're having trouble with Power Automate, please let me know. The best way to troubleshoot that will be with screenshots of each step.

For the record, if you want to test a script without building the flow, you can assign the input parameter some test data. That would look like this:
```
  workbookName = "TestBook";
  worksheetInformation = [{
    name: "Test1",
    data: [["A", "B"], ["1", "2"]]
  },
  {
    name: "Test2",
    data: [["A", "B"], ["3", "4"]]
  }];
```
That block would go before any other code inside the `main` function. Of course, it will overwrite anything provided by Power Automate, so be sure to remove it after testing.

One other little thing I noticed: the string on line 9 in your screenshot is using single quotes (') instead of ticks (`). 
![image](https://user-images.githubusercontent.com/38896772/166339616-1a2686fd-3e2e-4b54-8acf-74726b1e0508.png)
The ticks make it a [template](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), letting the variables inside the `${}`  be used. Otherwise, your worksheets will all be named "${workbookName}.${value.name}".

Please let me know if this information helps.

**Comment by JoannaNaomi** [comment]
HI Alex,

thank you very much for your help and detailed explanation! I got it working with your additional code describing the test data as above. I've also managed to get the power automate flow working too :)

**Comment by AlexJerabek** [comment]
That's awesome to hear! Glad everything's working smoothly now.

I'm going to close this issue, but if you have any other questions or issues, please let us know.
