### ISSUE TITLE
Read day-to-day changes

### ISSUE THREAD

**Issue by EKlein1206** [OfficeDev/office-scripts-docs#521]
It would be incredibly useful to have a script that can calculate the sum of the difference between 2 data points, then output that number so it could be used in Power Automate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c58cbf-aaf7-3d3a-48f4-ce9cebcf331c
* Version Independent ID: 74821d34-eab6-ec0f-7a9f-55aca81975d9
* Content: [Basic scripts for Office Scripts in Excel - Office Scripts](https://docs.microsoft.com/en-us/office/dev/scripts/resources/samples/excel-samples)
* Content Source: [docs/resources/samples/excel-samples.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/excel-samples.md)
* Product: **excel**
* Technology: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @EKlein1206,

Thank you for this sample request. Could you explain in a little more detail the data you're trying to retrieve from the workbook in this scenario? Are you looking for the script to return the difference between two cells, like what's stored in C1 of this screenshot?

![image](https://user-images.githubusercontent.com/38896772/178072550-0c3e8a52-5e50-4dde-aa00-9ca81e76c8e4.png)

**Comment by AlexJerabek** [comment]
Thank you for the clarification @EKlein1206. Let me see if I understand better and if this script helps you.

Here's a script that takes in a number from a flow, stores it in the next cell of column A, and returns the difference between the last two cells in column A. Please note that there's no error checking around the value, so the script will throw an error if the value from the form isn't a number. It also doesn't use the absolute value of the difference, so your flow will have to check both change possibilities.

```
function main(workbook: ExcelScript.Workbook, newData: string): number {
  // Add the new data to the worksheet.
  const sheet = workbook.getWorksheet("Tracking");
  const usedRange = sheet.getUsedRange();
  const previousEntry = usedRange.getRangeEdge(ExcelScript.KeyboardDirection.down);
  const newEntry = previousEntry.getOffsetRange(1, 0);
  newEntry.setValue(newData);

  // Return the difference between the previous and new cell values.
  return Number.parseFloat(newData) - (previousEntry.getValue() as number);
}
```

And here's the flow I used that in:
![image](https://user-images.githubusercontent.com/38896772/179289774-2ce1899f-b00e-4a83-b78c-72ea23b7df4e.png)

In doing this, I think I realized your challenge. Most of Power Automate's controls use strings as parameters instead of numbers. So, when you return the difference, it doesn't show up in the dynamic content list for a lot of fields. You can convent a number into a string with an Expression. When picking dynamic content, select Expression. Then, pick `string()`.

![image](https://user-images.githubusercontent.com/38896772/179290510-bead4d5d-7ef2-4c7d-9d39-16c907c3fe15.png)

After, put the cursor between the parentheses and switch to Dynamic content. There, select the result from the script.

![image](https://user-images.githubusercontent.com/38896772/179290785-cd049091-55d7-4d2d-9884-56ea35f12ba8.png)

Alternatively, you could change the script return type to a string (since the form returns data as a string, I made the script's `newData` parameter a string and assumed it'll actually be a number). However, this would prevent you from using the number in logical conditions in the flow, like this:

![image](https://user-images.githubusercontent.com/38896772/179291161-e1a10096-d780-4b10-a93e-5c2c220b8797.png)

Does this help provide clarity on using a returned value from a script as dynamic content? If so, I have a couple ideas for how to improve our documentation based on this exchange (including adding this scenario as a sample).

**Comment by EKlein1206** [comment]
There will be no issues with non-numbers being submitted with parameters on the form that will only allow numbers. However I just ran the script and it is throwing errors due to (newData). It also is not giving me a result/output currently.

I apologize as I am not the most well versed in this.
________________________________

**Comment by EKlein1206** [comment]
The first screenshot is what my excel table looks like, similar, however in a table and I include the date. The second is the script error I am receiving. My Form is very simple 2 question, Date selection from the calander, and a Short response question with number only parameters.
________________________________

**Comment by AlexJerabek** [comment]
Hi @EKlein1206,

I'm not seeing any screenshots. You may have to paste them directly into the reply on github.com (instead of through an email reply).

**Comment by EKlein1206** [comment]
Sorry About that, I hope these are visible
![Screenshot (3)](https://user-images.githubusercontent.com/108834925/179562989-0ce0f2cb-d270-401c-b3f0-ee45f27045ff.png)
![Screenshot (4)](https://user-images.githubusercontent.com/108834925/179562990-55253056-854c-46b9-9a09-b85866f44dd9.png)

**Comment by AlexJerabek** [comment]
Thanks @EKlein1206!

That error means one of the `getX` calls returned `undefined`. That means a part of the workbook the script expects does not exist. My guess is the error is with this line:
```
const sheet = workbook.getWorksheet("Tracking");
```

That code is getting a worksheet named "Tracking". If that worksheet doesn't exist in your workbook, anytime the script tries to use `sheet`, it'll fail. Replace Tracking with the name of your worksheet.

You can also use `getActiveWorksheet` to get the current worksheet, but that will be inconsistent with Power Automate. It'll assume the first
Please let me know if that gets you further.

**Comment by EKlein1206** [comment]
Hello, after trying to run the script with the change of name to what the worksheet is called, I am still getting an error on power automate
 "We were unable to run the script. Please try again.
Runtime error: Line 4: Cannot read property 'getUsedRange' of undefined
clientRequestId: b824223f-1574-4a3a-82d5-19afef2cfc92"
I'm sorry this is not an easy fix, I am hoping it can work

**Comment by AlexJerabek** [comment]
Hi @EKlein1206,

Sorry about the delay. Just to make sure we're on the same page, could you please provide your version of the script? "Runtime error: Line 4: Cannot read property 'getUsedRange' of undefined" means that the worksheet `getUsedRange` is being called on doesn't exist. Double-check the case-sensitivity and worksheet name, then send it over and we can continue debugging.

**Comment by EKlein1206** [comment]
<img width="685" alt="Annotation 2022-08-17 161425" src="https://user-images.githubusercontent.com/108834925/185234217-45ef0992-0c79-45db-b551-4fe1f7f1dffd.png">
I apologize for not copy and pasting it in but it is not formatting correctly and I wanted you to be able to see how it looks as well as the code itself.

**Comment by AlexJerabek** [comment]
Hi @EKlein1206,

Thanks for sharing the script. I tested it out on a local workbook with a worksheet named "1". I hit the same error as you when the worksheet had no content (it was completely empty). Is that the case for you?

My apologies for assuming the worksheet would always have data. In this empty worksheet scenario, you need to have a special case for when that happens. Additionally, I discovered my original suggestion would not work when the worksheet only had one value (`range.getRangeEdge` would take you to the very bottom of the spreadsheet). Here is my new script:

```
function main(workbook: ExcelScript.Workbook, newData: string): number {

  // Testing value
  newData = "5";

  const sheet = workbook.getWorksheet("1");
  const usedRange = sheet.getUsedRange();

  // If the worksheet is empty, add the value to the first space.
  if (!usedRange) {
    sheet.getRange("A1").setValue(newData);
    return;
  }

  const previousEntry = usedRange.getLastRow();
  const newEntry = previousEntry.getOffsetRange(1,0);
  newEntry.setValue(newData);

  let difference = Number.parseFloat(newData) - (previousEntry.getValue() as number);
  console.log(difference)
  return difference;
}
```

Please let me know if that unblocks you.

**Comment by EKlein1206** [comment]
If only it were that simple. As of today, I have 49 lines of data. Would It be useful if I took a screenshot of my table?

**Comment by AlexJerabek** [comment]
If you are comfortable sharing screenshots, then before and after screenshots would be very helpful.

**Comment by EKlein1206** [comment]
<img width="264" alt="Table" src="https://user-images.githubusercontent.com/108834925/185686626-fd45a54f-987b-49ef-b375-9b4b04b32f21.png">
<img width="960" alt="Script error-no changes to script" src="https://user-images.githubusercontent.com/108834925/185686989-23f3cd2a-65b4-4507-8e80-88ce04fd40c9.png">

I did not edit the script at all from the last set of pictures. I hope this is somewhat useful.

**Comment by AlexJerabek** [comment]
Thank you for the context. Let's take a step back, because I think I misunderstood the workbook early on and there are some things in the Script we can improve. There are often many different ways to achieve the same task in Office Scripts and which to choose depends on subtle factors, especially how neat and consistent the data is kept. My apologies for not understanding this and not correcting things sooner.

First, since everything is stored in a table, we should be using an ExcelScript.Table object to create and locate data. We can use `Table.addRow` and `Table.getColumn` to give us access without relying on specific cell numbers. The following script adds a provided value to a table, along with a date, and returns the difference from the Reading column. Some assumptions that are in this script:
- The table is named "Table1".
- The columns are order "Date" "Reading".
- There are only two columns (this is based off of the first screenshot you sent, not the latest ones - add values to the `newRow` array if there are more rows in the table).
- The testing value is there to run the script locally. It should be removed for use with Power Automate.

```
function main(workbook: ExcelScript.Workbook, newData: string) {
  // Give newData a test value.
  newData = "183350";

  // Get the table by its name.
  const table = workbook.getTable("Table1");

  // Read the current last entry in the Reading column.
  const readingColumn = table.getColumnByName("Reading");
  const readingColumnValues = readingColumn.getRange().getValues();
  const previousValue = readingColumnValues[readingColumnValues.length - 1][0] as number;

  // Add a row with the date and new value.
  const currentDate = new Date(Date.now()).toLocaleDateString();
  const newRow = [currentDate, newData];
  table.addRow(-1, newRow);

  // Return the difference between the newData and the previous entry.
  const difference = Number.parseFloat(newData) - previousValue;
  console.log(difference);
  return difference;
}
```

Here's the before and after screenshots:
![image](https://user-images.githubusercontent.com/38896772/186005349-1135b611-0de6-4e5c-80a5-f25d22e30fa7.png)
![image](https://user-images.githubusercontent.com/38896772/186005435-fab08df9-89ed-4158-bdf8-765c643c2420.png)
(Console output: 111)

**Comment by EKlein1206** [comment]
Well I am happy to announce that it works! Our only "issue" now is that that the result does not automatically populate into the 'Diff." column. However, until this point I have been manually dragging the formula for that column down for the autofill feature. I have tested the code through power automate and it sends an email out if it crosses a result of 500. 

Thank you so much for all of your help!

**Comment by AlexJerabek** [comment]
Glad to hear it's working!

As for the Diff column, you have a couple ways to fil that out with the script. For clarity, here's the table I'm working with. 
![image](https://user-images.githubusercontent.com/38896772/186724167-7cbbb655-0ec3-403b-aa2d-e1215b9fc971.png)

Option 1 is to add a formula in the `newRow`. Given the following table, you can use the formula `"=[@Reading]-OFFSET([@Reading],-1,0)"` in the Diff column. Here's the script (note that the only change is to the row being added):
```
function main(workbook: ExcelScript.Workbook, newData: string) {
  // Give newData a test value.
  newData = "184500";

  // Get the table by its name.
  const table = workbook.getTable("Table1");

  // Read the current last entry in the Reading column.
  const readingColumn = table.getColumnByName("Reading");
  const readingColumnValues = readingColumn.getRange().getValues();
  const previousValue = readingColumnValues[readingColumnValues.length - 1][0] as number;

  // Add a row with the date and new value.
  const currentDate = new Date(Date.now()).toLocaleDateString();
  const newRow = [currentDate, newData, "=[@Reading]-OFFSET([@Reading],-1,0)"];
  table.addRow(-1, newRow,);

  // Return the difference between the newData and the previous entry.
  const difference = Number.parseFloat(newData) - previousValue;
  console.log(difference);
  return difference;
}
```

Option 2 is to use the difference you calculate as the value. This adds a value instead of a formula to that column. Here's the script (note that `difference` is calculated earlier and passed to the table row):
```
function main(workbook: ExcelScript.Workbook, newData: string) {
  // Give newData a test value.
  newData = "184530";

  // Get the table by its name.
  const table = workbook.getTable("Table1");

  // Read the current last entry in the Reading column.
  const readingColumn = table.getColumnByName("Reading");
  const readingColumnValues = readingColumn.getRange().getValues();
  const previousValue = readingColumnValues[readingColumnValues.length - 1][0] as number;

  const difference = Number.parseFloat(newData) - previousValue;

  // Add a row with the date and new value.
  const currentDate = new Date(Date.now()).toLocaleDateString();
  const newRow = [currentDate, newData, difference];
  table.addRow(-1, newRow,);

  // Return the difference between the newData and the previous entry.
  console.log(difference);
  return difference;
}
```

There's also some fancy stuff you could do to recreate that manual AutoFill action you're currently doing. [Range.autoFill](https://docs.microsoft.com/en-us/javascript/api/office-scripts/excelscript/excelscript.range?view=office-scripts#excelscript-excelscript-range-autofill-member(1)) has the details, but I think that's more complicated than is warranted for this solution.
