### ISSUE TITLE
Issue in the sample

### ISSUE THREAD

**Issue by apcsb** [OfficeDev/office-scripts-docs#627]
The sample on this page is non-functional.
The sample in the training video differs from the sample in the article.
The getCommentByCell throws " The requested resource doesn't exist." errors and is wrapped in a try-catch block in the video.
Please fix (also, why doesn't it simply return null, is that a bug?)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62b95fcc-9e27-11a6-42a4-2f49a2a4edb4
* Version Independent ID: aff66a3a-30b7-0a85-4fea-a7682518a848
* Content: [Add comments in Excel - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/add-excel-comments)
* Content Source: [docs/resources/samples/add-excel-comments.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/add-excel-comments.md)
* Service: **excel**
* Sub-service: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by isabela-dominguez** [comment]
Hi @apcsb thank you for reaching out. 

@alison-mk would you please be able to investigate this issue?

**Comment by alison-mk** [comment]
Hi @apcsb, thanks for reporting these issues. 

The sample from the video is available here: https://github.com/sumurthy/officescripts-projects/blob/main/Add%20Excel%20Comments/AddComment.ts. The sample in the article isn't wrapped in a try-catch block because, per our performance guidance, invoking a try-catch inside a loop can lead to slow performance. I agree that it's confusing that the two samples don't match, and I'll update the article to clarify this difference. 

In either case — with or without the try-catch block — the sample is broken. It breaks at either getCommentByCell, or at addComment. I will research this issue internally and then update this GitHub issue, the sample, and the article when I have more information. 

Thank you! 
Alison

**Comment by AlexJerabek** [comment]
Hi @apcsb,

Sorry it's taken me a bit to get to this. I just created https://github.com/OfficeDev/office-scripts-docs/pull/635 to address this issue.  

The fix is to look for existing comments first and only try to delete the comment if it's there (avoiding the thrown error with getCommentByCell).

```
  // Find old comments, so we can delete them later.
  const oldCommentAddresses = scheduleSheet.getComments().map(oldComment => oldComment.getLocation().getAddress());

...

      // Delete old comments, so we avoid conflicts.
      if (oldCommentAddresses.find(oldCommentAddress => oldCommentAddress === commentCell.getAddress())) {
        const comment = workbook.getCommentByCell(commentCell);
        comment.delete();
      }
```

**Comment by AlexJerabek** [comment]
Hi @govert-w3s,

Could you please clarify what you mean by the method isn't working as documented? What behavior are you seeing that differs?
