### ISSUE TITLE
Excel Office Scripting default parameters

### ISSUE THREAD

**Issue by jcmontoya** [OfficeDev/office-scripts-docs#668]
[Enter feedback here]
In Excel:

I am using a button to call a script that takes a parameter. If I am using a default parameter, can I prevent the dialog box to display?

I don't want the user to do two clicks every single time.  

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 289cf0c9-3e47-ac7d-0c7d-4adab5930f74
* Version Independent ID: 289cf0c9-3e47-ac7d-0c7d-4adab5930f74
* Content: [Get user input for scripts - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/develop/user-input)
* Content Source: [docs/develop/user-input.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/develop/user-input.md)
* Service: **excel**
* Sub-service: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @jcmontoya,

Thanks for raising this. May I ask a question about your scenario? Since you have a default value for the parameter, where else are you providing input to that script if not from users? Is it part of a flow?

**Comment by jcmontoya** [comment]
I have the default value in the definition of the function. If there is a default value, I don't need to display the dialog box. If not default value, then we present the dialog for the user to input it. Thanks

**Comment by AlexJerabek** [comment]
Thanks for responding @jcmontoya.

I'm still confused on your scenario. If you remove the default value, aren't you editing the script? And when you say that when you provide the default value you don't want to prompt the user, does that imply that the value will never change? I guess I'm unclear as to when you want to use the parameters or not. In my head, it seems like you want two separate scripts because you're editing the script in these scenarios. 

Please correct me if I'm misreading or misunderstanding something.

**Comment by BasetsanaNjody** [comment]
@AlexJerabek even if he means the scripts must be separated.
is it possible for it to separate?

**Comment by BasetsanaNjody** [comment]
> Yes, you could save a copy of the script and edit the new one to be a version with hard-coded values. However, I think what you're getting at is that the codebases for the two scripts would diverge. Today, there is no way for two scripts to share code. If that feature would be useful, I'd encourage folks to submit that feedback through the Excel **Help** > **Feedback** tool.

okay
