### ISSUE TITLE
 'excelonlinebusiness' operation 'GetSingleScript' failed with status code 'BadRequest' "status": 400, "message": "Unable to parse script reference"

### ISSUE THREAD

**Issue by selthofer** [OfficeDev/office-scripts-docs#696]
At the step Run Script, when i fill in required inputs as given in the example, i get the error:

Failed to retrieve dynamic inputs. Error details: 'The dynamic operation request to API 'excelonlinebusiness' operation 'GetSingleScript' failed with status code 'BadRequest'. This may indicate invalid input parameters. Error response: { "status": 400, "message": "Unable to parse script reference.\r\nclientRequestId: 82cc7f18-8801-480e-a204-5b5c8dafd96d", "error": { "message": "Unable to parse script reference." }, "source": "excelonline-ne.azconn-ne-002.p.azurewebsites.net" }'

so no one explains how the File field can have Id from Crete File which is not yet created and yet next step Run Script actually depends on that but it is doing real-time checking before the automation is executed hence no file is really created. I did create Office Script in the Template.xlsx file and it is visible in my OneDrive but I am not sure why I am getting the error above then?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fdee872-3dfe-61b6-f824-dc8c74625c36
* Version Independent ID: c4481c81-ebae-7b3a-5da9-1757fb575188
* Content: [Convert CSV files to Excel workbooks - Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/convert-csv)
* Content Source: [docs/resources/samples/convert-csv.md](https://github.com/OfficeDev/office-scripts-docs/blob/main/docs/resources/samples/convert-csv.md)
* Service: **excel**
* Sub-service: **scripts**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @selthofer,

Thanks for reaching out. Let me see if I can help.

Just to be clear, we're talking about step 10, right? Where the "Convert CSV" script is run on each new .xlsx file?

The .xlsx file is created by step 9. It uses the blank Excel file template created by step 4. This means the script is run on an empty workbook. You should have the .xlsx files even without running the script in step 10 (they'll just be empty).

I can try and help debug your flow, though I need a little more context. One thought is that the dynamic content in the Excel Run Script block is pointing to the wrong "Id".  It should be the Id from step 9's Create file. Can you provide a screenshot of the Run script action? Also, does the flow run without the script step? It would only make empty .xlsx files, but that would help isolate where the problem is.

Thanks!
